---
apiVersion: v1
kind: Namespace
metadata:
  name: tests-whistlers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whistlers
  namespace: tests-whistlers
  labels:
    app: whistlers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whistlers
  template:
    metadata:
      labels:
        app: whistlers
    spec:
      containers:
      - name: flooder
        image: gyrt/logflooder
        imagePullPolicy: Always
        env:
        - name: RND
          value: "0"
        - name: DELAY
          value: "0.5"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-whistlers
  namespace: tests-whistlers
  labels:
    app: json-whistlers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: json-whistlers
  template:
    metadata:
      labels:
        app: json-whistlers
    spec:
      containers:
      - name: flooder
        image: gyrt/logflooder
        imagePullPolicy: Always
        env:
        - name: RND
          value: "0"
        - name: DELAY
          value: "0.5"
        - name: TYPE
          value: json
---
