---
apiVersion: v1
kind: Namespace
metadata:
  name: tests-whispers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whispers
  namespace: tests-whispers
  labels:
    app: whispers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whispers
  template:
    metadata:
      labels:
        app: whispers
    spec:
      containers:
      - name: flooder
        image: gyrt/logflooder
        imagePullPolicy: Always
        env:
        - name: RND
          value: "10"
        - name: DELAY
          value: "15"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-whispers
  namespace: tests-whispers
  labels:
    app: json-whispers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: json-whispers
  template:
    metadata:
      labels:
        app: json-whispers
    spec:
      containers:
      - name: flooder
        image: gyrt/logflooder
        imagePullPolicy: Always
        env:
        - name: RND
          value: "10"
        - name: DELAY
          value: "15"
        - name: LOG_TYPE
          value: json
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
